/* Write your PL/SQL query statement below */



WITH CTE AS 
(
SELECT DEPARTMENT.name AS DEPARTMENT, EMPLOYEE.name AS EMPLOYEE, EMPLOYEE.salary AS SALARY, 
RANK() OVER (PARTITION BY DEPARTMENT.name ORDER BY EMPLOYEE.salary DESC) AS RN
FROM EMPLOYEE 
JOIN DEPARTMENT 
ON EMPLOYEE.departmentId = DEPARTMENT.id
);
SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM CTE
WHERE RN = 1
